seozillabackend/Controllers/blogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using seozillabackend.DAL;
using seozillabackend.Models;

namespace seozillabackend.Controllers
{
    public class blogsController : Controller
    {
        private usercontext db = new usercontext();

        // GET: blogs
        public ActionResult Index()
        {
            var blogs = db.blogs.Include(b => b.order);
            return View(blogs.ToList());
        }

        // GET: blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: blogs/Create
        public ActionResult Create()
        {
            ViewBag.orderID = new SelectList(db.orders, "ID", "orderno");
            return View();
        }

        // POST: blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,daordered,wordcount,anchortext,targeturl,posttitle,postplacement,da,orderID")] blog blog)
        {
            if (ModelState.IsValid)
            {
                db.blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.orderID = new SelectList(db.orders, "ID", "orderno", blog.orderID);
            return View(blog);
        }

        // GET: blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            ViewBag.orderID = new SelectList(db.orders, "ID", "orderno", blog.orderID);
            return View(blog);
        }

        // POST: blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,daordered,wordcount,anchortext,targeturl,posttitle,postplacement,da,orderID")] blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.orderID = new SelectList(db.orders, "ID", "orderno", blog.orderID);
            return View(blog);
        }

        // GET: blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            blog blog = db.blogs.Find(id);
            db.blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

seozillabackend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

seozillabackend/Views/Shared/_blogdetailstable.cshtml
@model seozillabackend.Models.order


<div class="row">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    @*<th>Edit Order</th>*@
                   
                    <th>DA Ordered</th>
                    <th>Word Count Required</th>
                    <th>Anchor Text</th>
                    <th>Target URL</th>
                    <th>Post Title</th>
                    <th>Post Placement</th>
                    <th>DA</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var itemblog in Model.blogs)
                { 
                <tr>
                    @*<td><a href="update_blogger_outreach.html" class="btn btn-icon waves-effect waves-light btn-info m-b-5"><span class="fa fa-pencil"></span></a></td>*@
                   
                    <td>@Html.DisplayFor(modelitem=>itemblog.daordered)</td>
                    <td>@Html.DisplayFor(modelitem=>itemblog.wordcount)</td>
                    <td>@Html.DisplayFor(modelitem=>itemblog.anchortext)</td>
                    <td><a href="#">@Html.DisplayFor(modelitem=>itemblog.targeturl)</a></td>
                    <td>@Html.DisplayFor(modelitem=>itemblog.posttitle)</td>
                    <td>@Html.DisplayFor(modelitem=>itemblog.postplacement)</td>
                    <td>@Html.DisplayFor(modelitem=>itemblog.da)</td>
                    
                    <td>@Html.DisplayFor(item => Model.status)</td>
                    <td>@Html.ActionLink("Edit", "Edit", "blogs", new { id = itemblog.ID }, null)</td>
                   
                    @*<td><a class="label label-danger" title="This order will not be processed until payment has been made. Should payment not be made within 32 days your order will be cancelled automatically.">@Html.DisplayFor(item=>Model.status)</a></td>*@
</tr>
                }
                

        </table>
        @*<hr />
        <label>This is order date </label><label>@Model.ID</label>*@
       
    </div>
</div>

seozillabackend/Views/Shared/_citationdetailstable.cshtml
<div class="row">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Edit Order</th>
                    <th>Select Country</th>
                    <th>Business Name</th>
                    <th>Website URL</th>
                    <th>Brief Business Description (Max 100 Words)</th>
                    <th>Keywords (Max 5)</th>
                    <th>Founder / CEO</th>
                    <th>Full Address Inc Post / Zip Code</th>
                    <th>Phone Number</th>
                    <th>Listing Email Address</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><a href="update_local_business_citations.html" class="btn btn-icon waves-effect waves-light btn-info m-b-5"><span class="fa fa-pencil"></span></a></td>
                    <td>UK</td>
                    <td>nv</td>
                    <td>nvbnbv</td>
                    <td>vbvcbcb</td>
                    <td>bnvn</td>
                    <td>fdf</td>
                    <td>ffffd</td>
                    <td>dsd</td>
                    <td>djs</td>
                    <td><a class="label label-danger" title="This order will not be processed until payment has been made. Should payment not be made within 32 days your order will be cancelled automatically.">Awaiting Payment</a></td>
                </tr>




        </table>

    </div>
</div>


seozillabackend/Views/Shared/_layout_with_sidebar.cshtml
<!DOCTYPE html>
<html>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="SEOZILLA is a product to make SEO efficient">
    

    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <title>@ViewBag.Title | SEOZILLA - A SEO Buffet</title>

    @*Morris Chart CSS*@ 
    <link rel="stylesheet" href="~/assets/plugins/morris/morris.css">

    <!-- App css -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/assets/js/modernizr.min.js"></script>




</head>


<body class="fixed-left">

     @*Begin page*@ 
    <div id="wrapper">

        @*Top Bar Start*@
        <div class="topbar">

            @*LOGO*@
            <div class="topbar-left">
                <a href="current.html" class="logo"><span>SEO<span>ZILLA</span></span><i class="zmdi zmdi-layers"></i></a>
            </div>


            <div class="navbar navbar-default" role="navigation">
                <div class="container">

                    @*Page title*@
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <button class="button-menu-mobile open-left">
                                <i class="zmdi zmdi-menu"></i>
                            </button>
                        </li>
                        <li>
                            <h4 class="page-title"></h4>
                        </li>
                    </ul>


                </div> @*end container*@
            </div> @*end navbar*@
        </div>
        @*Top Bar End*@
        @*========== Left Sidebar Start ==========*@
        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">

                @*User*@
                <div class="user-box">

                    <h5><a href="#">Mat Helme</a> </h5>

                </div>
                @*End User*@
                @*- Sidemenu*@
                <div id="sidebar-menu">
                    <ul>
                        <li class="text-muted menu-title">Order</li>
                        <li>
                            <a href="add_new.html" class="waves-effect"><i class="fa fa-fw fa-plus-square"></i> <span>ADD NEW </span> </a>
                        </li>
                        <li>
                            <a href="current.html" class="waves-effect"><i class="fa fa-fw fa-list-alt"></i> <span>CURRENT</span> </a>
                        </li>
                        <li>
                            <a href="archived.html" class="waves-effect"><i class="fa fa-fw fa-archive"></i> <span>ARCHIVED</span> </a>
                        </li>

                        <li>
                            <a href="cancelled.html" class="waves-effect"><i class="fa fa-fw fa-trash"></i><span>CANCELLED</span> </a>
                        </li>

                    </ul>

                    <ul>
                        <li class="text-muted menu-title">My Account</li>

                        <li>

                            <a href="my_profile.html" class="waves-effect"><i class="fa fa-fw fa-user"></i><span>MY PROFILE</span></a>

                        </li>

                        <li>

                            <a href="view_invoices.html" class="waves-effect"><i class="fa fa-fw fa-file-text"></i> <span>VIEW INVOICES</span></a>

                        </li>

                        <li>
                            <a href="page-login.html">
                                <i class="fa fa-fw fa-power-off"></i> <span>LOG OUT</span>
                            </a>
                        </li>


                        <li>
                            <a href="#">
                                <i class="fa fa-fw fa-life-ring"></i><span> CONTACT SUPPORT</span>
                            </a>

                        </li>

                    </ul>





                    <div class="clearfix"></div>
                </div>
                @*Sidebar*@
                <div class="clearfix"></div>

            </div>

        </div>
        @*Left Sidebar End*@
        @RenderBody()
        <footer class="footer text-right">
            2018 - 2019 © SEOZILLA.
        </footer>
        

    </div>
        
    </div>

    
</div>
    @RenderSection("Scripts", false)
     @*END wrapper*@ 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>
        var resizefunc = [];

    </script>

    @*jQuery*@
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/detect.js"></script>
    <script src="~/assets/js/fastclick.js"></script>
    <script src="~/assets/js/jquery.blockUI.js"></script>
    <script src="~/assets/js/waves.js"></script>
    <script src="~/assets/js/jquery.nicescroll.js"></script>
    <script src="~/assets/js/jquery.slimscroll.js"></script>
    <script src="~/assets/js/jquery.scrollTo.min.js"></script>

    @*KNOB JS*@
    <!--[if IE]>
    <script type="text/javascript" src="~/assets/plugins/jquery-knob/excanvas.js"></script>
    <![endif]-->




    <script src="~/assets/plugins/jquery-knob/jquery.knob.js"></script>

    @*Morris Chart*@
    <script src="~/assets/plugins/morris/morris.min.js"></script>
    <script src="~/assets/plugins/raphael/raphael-min.js"></script>

    @*Dashboard init*@
    <script src="~/assets/pages/jquery.dashboard.js"></script>

    @*App js*@
    <script src="~/assets/js/jquery.core.js"></script>
    <script src="~/assets/js/jquery.app.js"></script>

    <script>
        $(document).ready(function () {

            var originalContent = $('.label-danger').html();

            $(".label-danger").hover(function () {

                $(this).html('<strong>Make Payment</strong>').css({ "background": "#10c469" });

            }, function () {
                $(this).html(originalContent).css({ "background": "#ff5b5b" });

            });

        });

    </script>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>
        var resizefunc = [];

    </script>

    @*jQuery*@
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/detect.js"></script>
    <script src="~/assets/js/fastclick.js"></script>
    <script src="~/assets/js/jquery.blockUI.js"></script>
    <script src="~/assets/js/waves.js"></script>
    <script src="~/assets/js/jquery.nicescroll.js"></script>
    <script src="~/assets/js/jquery.slimscroll.js"></script>
    <script src="~/assets/js/jquery.scrollTo.min.js"></script>

    <!-- KNOB JS -->
        <!--[if IE]>
        <script type="text/javascript" src="~/assets/plugins/jquery-knob/excanvas.js"></script>
        <![endif]-->
    <script src="~/assets/plugins/jquery-knob/jquery.knob.js"></script>

    @*Morris Chart*@
    <script src="~/assets/plugins/morris/morris.min.js"></script>
    <script src="~/assets/plugins/raphael/raphael-min.js"></script>

    @*Dashboard init*@
    <script src="~/assets/pages/jquery.dashboard.js"></script>

    @*App js*@
    <script src="~/assets/js/jquery.core.js"></script>
    <script src="~/assets/js/jquery.app.js"></script>

    <script>
        $(document).ready(function () {
            

            var originalContent = $('.label-danger').html();

            $(".label-danger").hover(function () {

                $(this).html('<strong>Make Payment</strong>').css({ "background": "#10c469" });

            }, function () {
                $(this).html(originalContent).css({ "background": "#ff5b5b" });

            });

            $(".zmdi-menu").click(function () {
                
                $("div#wrapper").toggleClass("enlarged");
            });



        });

    </script>

</body>


</html>